### ISSUE TITLE
Doesn't work  (With EBU-TT-D)

### ISSUE THREAD

**Issue by ghost** [Aasim-A/yt-xml2vtt#2]
(node:52220) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'text' of undefined
    at D:\Users\joshu\Documents\Development\xml2vttlive\node_modules\yt-xml2srt\src\Xml2Srt.js:19:37
    at new Promise (<anonymous>)
    at Object.Parse (D:\Users\joshu\Documents\Development\xml2vttlive\node_modules\yt-xml2srt\src\Xml2Srt.js:16:10)
    at D:\Users\joshu\Documents\Development\xml2vttlive\routes\xml2vtt.js:11:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Aasim-A** [comment]
can you post the code that's causing this error?
